home/urls.py
from django.urls import path
from .views import *

urlpatterns =[
	
	
	
	
	#INICIO 
#url de registro
	path('registrar/',vista_register,name="vista_register"),
	path('inicio/',vista_inicio,name='vista_inicio'),
	path('',vista_login,name='vista_login'),
	path('logout/',vista_logout,name="vista_logout"),
#---------------------------------------------------------------------------------------------------------------------
	#BODREGA MATERIAL

	
	path('get1/',get1,name='get1'),
	# # path('get/',get,name='get'),
	path('b/',busqueda,name='busqueda'),
	path('ver_detalle',detalle_ver,name='detalle_ver'),
	path('agrr_bodega_material',agr_bodega_materiall,name='agr_bodega_materiall'),
	path('editar_bodega_material/<int:id_bdm>/',editar_bodega_material,name="editar_bodega_material"),
	path('eliminar_bodega_material/<int:id_bdm>/',eliminarr_bodega_material,name="eliminarr_bodega_material"),
#-----------------------------------------------------------------------------------------------------------------
#urls de nombre_material
	path('agregar_nombre_material/',vista_agregar_nombre_material,name="vista_agregar_nombre_material"),
	path('editar_nombre_material/<int:id_nm>/',vista_editar_nombre_material,name="vista_editar_nombre_material"),
	path('eliminar_nombre_material/<int:id_nm>/',vista_eliminar_nombre_material,name="vista_eliminar_nombre_material"),
	path('lista_nombre_material/',vista_lista_nombre_material,name="vista_lista_nombre_material"),
#---------------------------------------------------------------------------------------------------------------
	# Detalle_Prestamo

	path('ListaD/',lista_DetallePrestamo,name='lista_DetallePrestamo'),
	path('verD/<int:id_Dprest>/',ver_DetallePrestamo,name='ver_DetallePrestamo'),
	path('eliminarD/<int:id_Dprest>/',elimnar_DetallePrestamo,name='elimnar_DetallePrestamo'),
#----------------------------------------------------------------------------------------------------------------
	#urls de marca
	path('lista_marca/',vista_lista_marca,name="vista_lista_marca"),
	path('agregar_marca/',vista_agregar_marca,name="vista_agregar_marca"),
	path('editar_marca/<int:id_marca>/',vista_editar_marca,name="vista_editar_marca"),
	path('eliminar_marca/<int:id_marca>/',vista_eliminar_marca,name="vista_eliminar_marca"),
#----------------------------------------------------------------------------------------------------------------
	#urls de materiales
	path('agregar_material/',vista_agregar_material,name="vista_agregar_material"),
	path('lista_material/',vista_lista_material,name="vista_lista_material"),
	path('editar_material/<int:id_material>/',vista_editar_material,name="vista_editar_material"),
	path('eliminar_material/<int:id_material>/',vista_eliminar_material,name="vista_eliminar_material"),
	path('ver_material/<int:id_material>/',vista_ver_material,name="vista_ver_material"),
	path('materiales_no_disponibles',vista_materiales_no_disponibles,name="vista_materiales_no_disponibles"),
#----------------------------------------------------------------------------------------------------------
#urls de devoluciones
	path('devolucion/<int:id_prest>/',devolucion_prestamo,name='devolucion_prestamo'),
#------------------------------------------------------------------------------------------------------------------	
	#urls de prestamo
	path('Lista/',lista_prestamo,name='lista_prestamo'),
	path('Agregar/',agregar_prestamo,name='agregar_prestamo'),
	path('editar/<int:id_prest>/',editar_prestamo,name='editar_prestamo'),
	path('elimnar/<int:id_prest>/',eliminar_prestamo,name='eliminar_prestamo'),
#------------------------------------------------------------------------------------------------------------------
	#urls de la tabla categoria
	path('categoria/',nombre_categoria,name="nombre_categoria"),
	path('editar_categoria/<int:id_cat>/',editarr_categoria,name='editarr_categoria'),
	path('agregar_categoria/',agr_categoria,name='agr_categoria'),
	path('eliminar_categoria/<int:id_cat>/',eliminarr_categoria,name='eliminarr_categoria'),

#--------------------------------------------------------------------------------------------------------------------
	# AQUI INICIAN LAS URLS DE BODEGA-----
	path('lista_bodega/',vista_lista_bodega, name='vista_lista_bodega'),
	path('ver_bodega/<int:id_bod>/',vista_ver_bodega,name='vista_ver_bodega'),
	path('agregar_bodega/',vista_agregar_bodega,name='vista_agregar_bodega'),
	path('editar_bodega/<int:id_bod>/',vista_editar_bodega, name= 'vista_editar_bodega'),
	path('eliminar_bodega/<int:id_bod>/',vista_eliminar_bodega, name= 'vista_eliminar_bodega'),

	# AQUI TERMINAN LAS URLS DE BODEGA-----

#----------------------------------------------------------------------------------------------------------------
	#urls de la tabla cuentadante
	path('vista_cuentadante',lista_cuentadante,name ='lista_cuentadante'),
	path('agr_cuentadante',agregar_cuentadante,name='agregar_cuentadante'),
	path('editar_cuentadante/<int:id_cue>/',editarr_cuentadante,name='editarr_cuentadante'),
	path('eliminar_cuentadante/<int:id_cue>/',eliminarr_cuentadante,name='eliminarr_cuentadante'),

#-----------------------------------------------------------------------------------------------------------------
	#urls de la tabla programa
	path('lista_programas/',vista_lista_programas, name = 'vista_lista_programas'),
	path('agregar_programas/',vista_agregar_programas, name = 'vista_agregar_programas'),
	path('editar_programas/<int:id_pro>/',vista_editar_programas, name = 'vista_editar_programas'),
	path('eliminar_programas<int:id_pro>/', vista_eliminar_programas, name='vista_eliminar_programas'),

#-----------------------------------------------------------------------------------------------------------------
	#urls de la tabla FICHA
	path('ver_ficha',detalle_ficha,name='detalle_ficha'),
	path('agregar_ficha',agr_ficha,name='agr_ficha'),
	path('editar_ficha/<int:id_fic>/',edit_ficha,name='edit_ficha'),
	path('eliminar_ficha/<int:id_fic>/',elim_ficha,name='elim_ficha'),

#-----------------------------------------------------------------------------------------------------------------
	#APRENDIZ
	path('lista_aprendiz/',vista_lista_aprendiz,name='vista_lista_aprendiz'),
	path('agregar_aprendiz/',vista_agregar_aprendiz,name='vista_agregar_aprendiz'),
	path('eliminar_aprendiz/<int:id_apr>/', vista_eliminar_aprendiz, name='vista_eliminar_aprendiz'),
	path('editar_aprendiz/<int:id_apr>/',vista_editar_aprendiz,name='vista_editar_aprendiz'),

#----------------------------------------------------------------------------------------------------------------
#urls de reportes
	path('reporte/',vista_reporte,name="vista_reporte"),
	path('materiales_disponibles/',vista_materiales_disponibles,name="vista_materiales_disponibles"),
	path('reporte_material/',vista_reporte_material,name="vista_reporte_material"),
	path('reportes/',vista_reportes,name="vista_reportes"),
	
	
]

preIser/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('service.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
import time
#formulario de registro
class register_form(forms.Form):
	username =forms.CharField(widget=forms.TextInput(attrs={
		'id':'username','class':'form-control','placeholder':'Nombre de Usuario','autofocus':'autofocus',
		}))
	email    =forms.EmailField(widget=forms.TextInput(attrs={
		'id':'email','class':'form-control','placeholder':'Correo Electronico','autofocus':'autofocus',
		}))
	password_1 = forms.CharField(widget=forms.PasswordInput(render_value=False,attrs={
		'id':'password','class':'form-control','placeholder':'Contraseña','autofocus':'autofocus',
		}))
	password_2 = forms.CharField(widget=forms.PasswordInput(render_value=False,attrs={
		'id':'password2','class':'form-control','placeholder':'placeholder','autofocus':'autofocus',
		}))

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			u= User.objects.get(username=username)
		except User.DoesNotExist:
			return username
		raise forms.ValidationError('Nombre de Usuario ya Registrado')

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			email = User.objects.get(email=email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('Correo Electronico ya Existe')

	def clean_password_2(self):
		password_1 =self.cleaned_data['password_1']
		password_2 =self.cleaned_data['password_2']
		if not len(password_1)>7:
			raise forms.ValidationError('La contraseña debe contener minimo 8 caracteres')
		else:
			pass 
		if password_1==password_2:
			pass
		else:
			raise forms.ValidationError('Las contraseñas no coinciden')
class login_form (forms.Form):
	user = forms.CharField(widget=forms.TextInput(attrs={'class':'input100','name':'username',
														'placeholder':'Nombre de Usuario'}))
	password= forms.CharField(widget=forms.PasswordInput(render_value=False,attrs={'class':'input100',
													'name':'pass','placeholder':'Contraseña'}))
#formulario de la tabla nombre_material
class agregar_nombre_material_form(forms.ModelForm):
	class Meta:
		model = Nombre_Material
		fields = '__all__'
		widgets = {
			'nombre' : forms.TextInput(attrs={
			'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}

#formulario de la tabla material
class agregar_material_form(forms.ModelForm):
	tipo_elemento = forms.ChoiceField(choices=([('Devolutivo','Devolutivo'), ('Consumible','Consumible') ]), initial='1', required = True,)
	class Meta:
		model = Material
		fields = '__all__'
#fromulario de la tabla material
class agregar_marca_form(forms.ModelForm):
	class Meta:
		model = Marca
		fields = '__all__'
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}
#formularios de la tabla prestamo
# documentar
class agregar_prestamoF(forms.ModelForm):
	aprendiz = forms.CharField(widget=forms.TextInput(attrs={'id':'busquedProyecto',
														'placeholder':'identificacion del aprendiz'}))

	class Meta:
		model=Prestamo
		exclude =['estado']
		fields=['fecha_prestamo','fecha_entrega']#,'aprendiz']
		widgets = {
					'fecha_prestamo':forms.TextInput(attrs={'class':'datepicker'}),
					'fecha_entrega' : forms.TextInput(attrs={'class':'datepicker'})
		}
		
	def clean(self):
		cleaned_data = super(agregar_prestamoF,self).clean()
		fecha_prestamo =self.cleaned_data['fecha_prestamo']
		fecha_entrega = self.cleaned_data['fecha_entrega']
		fecha_actual = time.strftime("%Y-%m-%d")
		if str(fecha_prestamo)>str(fecha_actual):
			raise forms.ValidationError('La Fecha de prestamo no debe ser mayor a la fecha actual')
		elif str(fecha_prestamo)<str(fecha_actual):
			raise forms.ValidationError('La Fecha de prestamo no debe ser menor a la fecha actual')
		elif fecha_entrega < fecha_prestamo:
			raise forms.ValidationError('La fecha de entrega no debe ser menor a la fecha de prestamo') 
		elif str(fecha_actual)==str(fecha_prestamo):
			pass
		return cleaned_data
# documentar

class agregar_DPrestamoF(forms.ModelForm):
	try:
		material=forms.ModelChoiceField(queryset=Material.objects.filter(estado='Disponible'))
	except:
		print ("vvvvvvvvvvvvvv")
		print ("ERROR CONSULTA")
		print ("vvvvvvvvvvvvvv")
	
	class Meta:
		model=Detalle_Prestamo
		fields=['material','cantidad']
		widgets={
			'material':forms.Select(attrs={'required':'true'}),
			'cantidad' :forms.TextInput(attrs={'type':'number','min':'0'}),

		}
class editar_DPrestamoF(forms.ModelForm):
	material = Material.objects.filter(estado="No Disponible")
	class Meta:
		model=Detalle_Prestamo
		fields=['material','cantidad']
		widgets={
		'material':forms.Select(attrs={
			'required':'true'
			})
		}
#-----------------------------------------------------------------------------------------------------

class dev_prestamoF(forms.ModelForm):
	fecha_prestamo=forms.DateField(disabled=True)
	estado=forms.ChoiceField(choices=([('Activo','Activo'),('Terminado','Terminado')]),disabled=True)
	aprendiz=forms.ModelChoiceField(Aprendiz.objects.all(),disabled=True)
	fecha_entrega=forms.DateField(disabled=True)

	class Meta:
		model=Prestamo
		fields='__all__'

class dev_DPrestamoF(forms.ModelForm):
	material=forms.ModelChoiceField(Material.objects.all(),disabled=True)
	estado_devolucion=forms.ChoiceField(widget=forms.Select(attrs={
		'class':'estado'
		}) ,choices=([('bueno','bueno'),('malo','malo')]))
	cantidad=forms.IntegerField()
	estado_elemento_prestamo=forms.ChoiceField(choices=([('En Prestamo','En Prestamo'),('Entregado','Entregado')]))
	tipo_daño=forms.ChoiceField(widget=forms.Select(attrs={
		'class':'tipo'
		}),label='Tipo de Daño', choices=([('Fisico','Fisico'),('Logico','Logico')]))



	class Meta:
		model=Detalle_Prestamo

		fields='__all__'
		widgets={
		'cantidad':forms.TextInput(attrs={
		'id':'contador'
		}),
		'fecha_devolucion' : forms.TextInput(attrs={
			'class':'datepicker'
		}),
		}
#-----------------------------------------------------------------------------------------
class det_prestamoF(forms.ModelForm):
	fecha_prestamo=forms.DateField(disabled=True)
	estado=forms.ChoiceField(choices=([('Activo','Activo'),('Terminado','Terminado')]),disabled=True)
	aprendiz=forms.ModelChoiceField(Aprendiz.objects.all(),disabled=True)
	fecha_entrega=forms.DateField(disabled=True)

	class Meta:
		model=Prestamo
		fields='__all__'

class det_DPrestamoF(forms.ModelForm):
	material=forms.ModelChoiceField(Material.objects.all(),disabled=True)
	estado_devolucion=forms.ChoiceField(choices=([('bueno','bueno'),('malo','malo')]))
	cantidad=forms.IntegerField(disabled=True)
	estado_elemento_prestamo=forms.ChoiceField(choices=([('En Prestamo','En Prestamo'),('Entregado','Entregado')]))
	tipo_daño=forms.ChoiceField(choices=([('Fisico','Fisico'),('Logico','Logico')]))



	class Meta:
		model=Detalle_Prestamo
		fields='__all__'

#formulario de la tabla categoria
class categoria_form(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = '__all__'
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id':'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}

#formulario de la tabla bodega
class agregar_bodega_form(forms.ModelForm):
	class Meta:
		model= Bodega
		fields= '__all__'
		widgets = {
			'nombre': forms.TextInput(attrs={
				'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
				}),
		}

#formulario de la tabla cuentadante
class cuentadante_form(forms.ModelForm):
	class Meta:
		model = Cuentadante
		fields = '__all__' 
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id':'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		'identificacion' : forms.TextInput(attrs={
			'id' : 'identificacion','class':'form-control','placeholder':'Identificacion',
										'autofocus': 'autofocus','type':'number'
			}),
		}

#formulario de la tabla programa
class agregar_programas_form(forms.ModelForm):
	class Meta:
		model = Programa
		fields ='__all__'
		widgets = {
			'nombre' : forms.TextInput(attrs={
				'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
				}),
		}

class ficha_form(forms.ModelForm):
	class Meta:
		model = Ficha
		fields = '__all__'
		widgets= {
			'numero_ficha' : forms.TextInput(attrs={
				'id' : 'ficha','class':'form-control','placeholder':'Numero de Ficha',
										'autofocus': 'autofocus','type':'number'
				}),
			'fecha_inicio' : forms.TextInput(attrs={
				'id':'fecha_inicio','class':'datepicker form-control','placeholder':'Fecha de Inicio',
										'autofocus': 'autofocus'
				}),
			'fecha_finalizacion' : forms.TextInput(attrs={
				'id':'fecha_finalizacion','class':'datepicker form-control','placeholder':'Fecha de Finalizacion',
										'autofocus': 'autofocus'
				}),
		}


#formulario de la tabla bodega_material
class Bodega_Material_form(forms.ModelForm):
	class Meta:
		model = Bodega_Material
		fields = ['bodega','fecha_ingresa']
		widgets= {
			'fecha_ingresa' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),
			'fecha_salida' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),

		}
		labels = {
		'bodega':'Ambiente'
		}
	def clean_fecha_ingresa(self):
		fecha_ingresa =self.cleaned_data['fecha_ingresa']
		fecha_actual = time.strftime("%Y-%m-%d")
		if str(fecha_actual)==str(fecha_ingresa):
			pass
		elif str(fecha_ingresa)>str(fecha_actual):
			raise forms.ValidationError('La Fecha de ingreso no debe ser mayor a la fecha actual')
		return fecha_ingresa
class editar_bodega_material_form(forms.ModelForm):
	class Meta:
		model = Bodega_Material
		fields = '__all__'
		widgets= {
			'fecha_ingresa' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),
			'fecha_salida' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),

		}
		labels = {
		'bodega':'Ambiente'
		}

templates/agregar_aprendiz.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
Agregar Aprendiz
{% endblock %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
	<h3>Agregar Aprendiz</h3>
  <br>
	<form action="" method="POST">
		{% csrf_token %}
		    <div class="form-group">
              <div >
                <div >
                	{{formulario.nombre.errors}}
                  <div class="form-label-group">
                    {{formulario.nombre}}
                    <label for="nombre">Nombres y Apellidos</label>
                  </div>
                </div>
              </div>
           </div>

           <div class="form-group">
              <div >
                <div >
                	{{formulario.identificacion.errors}}
                  <div class="form-label-group">
                    {{formulario.identificacion}}
                    <label for="identificacion">Numero de Identificacion</label>
                  </div>
                </div>
              </div>
           </div>

            <div class="form-group">
              <div >
                <div >
                  {{formulario.tipo_documento.errors}}
                  <div class="form-label-group">
                    {{formulario.tipo_documento}}
                    <label for="tipo_documento">Tipo de Documento</label>
                  </div>
                </div>
              </div>
           </div>

            <div class="form-group">
              <div >
                <div >
                  {{formulario.estado.errors}}
                  <div class="form-label-group">
                    {{formulario.estado}}
                    <label for="{{formulario.estado.id_for_label}}">Estado</label>
                  </div>
                </div>
              </div>
           </div>

           <div class="form-group">
              <div >
                <div>
                  {{formulario.ficha.errors}}
                  <div class="form-label-group">
                    {{formulario.ficha|bootstrap}}
                  </div>
                </div>
              </div>
           </div>
        <button class="btn btn-success">Registrar Aprendiz</button>
		<br>
           <br>
           <a href="{% url 'vista_lista_aprendiz'%}" class="btn btn-primary">Regresar</a>
	</form>		
		</div>
  </div>
{% endblock %}

templates/agregar_bodega_material.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
	Agregar bodega_material
{% endblock titulo %}
{% block contenido %}

<form action="" method="POST" enctype="multipart/form-data">

	{% csrf_token %}
	{{formulario|bootstrap}}
	<div class="col-md-3 text-center">
		<button class="btn btn-success">Registrar</button>
	</div>
</form>
<br>
	
{% endblock contenido %}

templates/agregar_prestamo.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
 Prestamo
{% endblock titulo %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
      <form action="" method="POST" >
          
        {% csrf_token %}
            <div >
                  <h3>Agregar Prestamo</h3>
                  <br>
                {{formulario|bootstrap}}
                <div>
                  <p id="datos1"></p>
                <p  style="font-size:22px;" id="datos" ></p>
          
                </div>
                
                {{ formset.management_form }}
            </div> 
            <div >
                    <h5 id="texto">No se permite repetir elementos con mismo codigo sena o serial</h5> 
                  {% for form in formset %}                
                        <div class="link-formset">
                          <fieldset id="f">
                            {{ form.id }}
                            <ul>
                                <div class="row">
                                  <div  class="col-12">{{form.material|bootstrap}}</div>
                                  <div class="col-5">{{form.cantidad|bootstrap}}</div>
                                  <div class="col-2">{{form.DELETE|bootstrap}}</div>                              
                                </div>                
                            </ul>
                            </fieldset>
                        </div>
                    
                  {% endfor %}       
            </div>
                    
        <br>
        <input type="submit" value="AGREGAR PRESTAMO">
       

  </form>

  </div>
</div>
<script >
//   $('#busquedProyecto').on('change',inicio1);
//   function inicio1() {
//     var id = $(this).val();  
//     console.log(id+"esot w ")  
//     $.ajax({
//       data:{'id':id},
//       url:'/get1',
//       type:'get',
//       success:function(data){
//         var html=""
//         for (var i = 0; i < data.length; i++) {
//           html+='<ul><li>'+data[i].fields.numero_ficha+'</li></ul>'

//         }
//         $('#datos1').html(html);
//       }

//     });
//   }

// // </script>

 <script type="text/javascript">
 $('#busquedProyecto').keyup(function(e){
    consulta = $("#busquedProyecto").val();
    console.log(consulta)
    $.ajax({
    data: {'nombre': consulta},
    url: '/get1/',
    type: 'get',
    success : function(data) {
          var html=""
          for (var i = 0; i < data.length; i++) {
            html+='<ul><li>'+data[i].numero_ficha+'</li></ul>'

        }

         $('#datos1').html(html);
    },
    error : function(message) {
            console.log(message);
         }
   });

  });


    $('#busquedProyecto').keyup(function(e){
    consulta = $("#busquedProyecto").val();
    console.log(consulta)
    $.ajax({
    data: {'nombre': consulta},
    url: '/b/',
    type: 'get',
    success : function(data) {
          var html=""
          for (var i = 0; i < data.length; i++) {
            html+='<ul><li>'+data[i].nombre+'</li></ul>'

        }

         $('#datos').html(html);
    },
    error : function(message) {
            console.log(message);
         }
   });

  });



</script>
    <script>
    $('.link-formset').formset({
        addText: 'Agregar Elemento',
        deleteText: 'eliminar'
    });
</script>
  <script >
    $.datepicker.regional['es']={
      closeText:'Cerrar',
      prevText:'Anterior',
      nextText:'Siguiente',
      currenText:'Hoy',
      monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
      monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
      dayNames:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
      dayNamesShort:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
      dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
      firstDay:1,
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $('.datepicker').datepicker();
  </script>
{% endblock contenido %}

templates/agregar_programa.html
{% extends "base.html" %}
{%block titulo%}
	agregar programa

{%endblock%}

{%block contenido%}
<div id="cajota">
  <div id="centrar">
    <h3>Agregar Programa</h3>
  <br>
	<form action="" method="POST">
		{% csrf_token %}
		    <div >
              <div >
                <div >
                	{{formulario.nombre.errors}}
                  <div class="form-label-group">
                    {{formulario.nombre}}
                    <label for="nombre">nombre</label>
                  </div>
                </div>
              </div>
           </div>
           <br>
        <button class="btn btn-success">Registrar Programa</button>
        
	</form>
  <br>
	<a href="{% url 'vista_lista_programas'%}" class="btn btn-primary">Regresar</a>
  
</div>
</div>
{%endblock%}

templates/vista_agregar_material.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
  Agregar Material
{% endblock titulo %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
    <h3>Agregar Material</h3>
  <br>
  <h5>
    {{ msj_bod }}
  </h5>
  <form action="" method="POST" name="f1" id="f1">
      {% csrf_token %}
      <div >
          {{formulario|bootstrap}}
          {{ bod.management_form }}
          {% for form in bod %}
          <div class="link-formset">
              {{ form.id }}
              <div class="row">
                <div class="col-6">{{form.bodega|bootstrap}}</div>
                <div class="col-6">{{form.fecha_ingresa|bootstrap}}</div>     
              </div>
          </div>
          {% endfor %}
          <button class="btn btn-success" type="submit">Guardar nuevo material</button>
      </div>
  </form>  <br>
  <a class="btn btn-secondary btn-sm" href="{% url 'vista_lista_material' %}">Regresar a la lista</a>
</div>
</div>


  <script type="text/javascript">
  	$(document).ready(function(){
			$('#id_cantidad').attr('disabled','disabled');
			$('#id_tipo_elemento').on('change',function(){
			var selectValor = '#'+$(this).val();
			if (selectValor=='#Devolutivo') {
				$('label[for="id_codigo_sena"]').show();
				$('#id_codigo_sena').show();
				$('#id_cantidad').attr('disabled','disabled');
			}
			else{
				$('#id_codigo_sena').hide();
				$('label[for="id_codigo_sena"]').hide();
        $('label[for="id_numero_serie"]').hide();
        $('#id_numero_serie').hide();
				document.f1.id_cantidad.disabled=false;
			}
		});
	});
  </script>
  <script >
    $.datepicker.regional['es']={
      closeText:'Cerrar',
      prevText:'Anterior',
      nextText:'Siguiente',
      currenText:'Hoy',
      monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
      monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
      dayNames:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
      dayNamesShort:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
      dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
      firstDay:1,
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $('.datepicker').datepicker();
  </script>

{% endblock contenido %}